yt-dlp: Prefer m4a or ogg for audio (don't reencode lossy), mkv for video (even if not merging)
Initially I had opus>ogg in here as well, but this causes an error when
embedding a thumbnail:

  mutagen.oggvorbis.OggVorbisHeaderError: no appropriate stream found

Turns out .ogg should *only* be Vorbis. The correct extension for Opus
is .opus, which is in fact an Opus stream in an OGG container and not
the raw audio stream like with .aac:

  https://wiki.xiph.org/MIME_Types_and_File_Extensions